/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './clipboard.module';
import * as import2 from '@angular/core/src/di/injector';
class ClipboardModuleInjector extends import0.NgModuleInjector<import1.ClipboardModule> {
  _ClipboardModule_0:import1.ClipboardModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.ClipboardModule {
    this._ClipboardModule_0 = new import1.ClipboardModule();
    return this._ClipboardModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.ClipboardModule)) { return this._ClipboardModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ClipboardModuleNgFactory:import0.NgModuleFactory<import1.ClipboardModule> = new import0.NgModuleFactory(ClipboardModuleInjector,import1.ClipboardModule);